[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_wtf = "FhpcYtvyN8PZFZxjGJ1GuaDg7dLLajsP8jHoseQwZdeY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mikemaccana/.config/solana/id.json"

[scripts]
test = "npx esrun tests/anchor-wtf.test.ts"
